server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 10MB

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_commerce"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tatriet16@gmail.com
    password: qoaputtijsolpzxv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
